name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.0.app

      - name: Swift Version
        run: swift --version

      - name: Build SDK
        run: swift build -c release

      - name: Run Tests
        run: swift test

      - name: Build Example App
        run: |
          cd Examples/RealtimeExample
          xcodebuild -scheme RealtimeExample \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            clean build \
            CODE_SIGNING_ALLOWED=NO
